### ISSUE TITLE
Please consider loosen the license

### ISSUE THREAD

**Issue by tony84727** [AllJointTW/TonJS#30]
There are two contributors now, two human and one bot. I will like to bring this up when it's still possible to reach all of the authors.

Not a lawyer but AFAIK, GPL is a strong license that forces any works derived from GPL licensed project also to be licensed under GPL, which means projects based on this framework have to be open-sourced as well. Would you consider loosen the license to a weaker one like LGPL? Or will there be a separate (probably charged) license for closed-source projects?

**Comment by trylovetom** [comment]
Hi @tony84727 I has been long time since I saw you last. You are correct, GPL is viral. It can infection another code. But don't be afraid of it. It can push the open source community to more active. You can mail me to get the MIT license. We also have the sponsor plan ($5/month for personal use, $50/month for commercial use) for closed-source project soon. Buy the coffee or breakfast for us. We will make it better than better.
